version: "3.9"
services:
  mongodb:
    container_name: 'mongodb-websocket'
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports: 
      - "27017:27017"
    # networks:
    #     - backend
    # network_mode: "bridge"
    
  mongo-express:
    container_name: 'mongodb-express-websocket'
    image: mongo-express
    depends_on: 
      - mongodb
    # restart: unless-stopped
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: localhost
    networks:
      - backend
    # network_mode: "bridge"

networks:
  backend:
    # network_mode: 
    #   - bridge