version: "3.9"
services:
  mongodb:
    container_name: 'mongodb-websocket'
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 27017:27017
    # networks:
    #     - backend
    network_mode: "bridge"
    
  mongo-express:
    container_name: 'mongodb-express-websocket'
    image: mongo-express
    depends_on: 
      - mongodb
    # restart: unless-stopped
    ports: 
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_SERVER: 127.0.0.1
    # networks:
    #   - backend
    network_mode: "bridge"

networks:
  backend:
    # network_mode: 
    #   - bridge